#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: price
    group: products-store-project
  name: price-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: price
  template:
    metadata:
      labels:
        app: price
        group: products-store-project
    spec:
      serviceAccountName: k8s-products-sa
      containers:
      - image: ghcr.io/uliseslarraga/open-telemetry-demo/price-service:main
        name: price
        imagePullPolicy: Always
        env:
          - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
            value: "true"
          - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
            value: "true"

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: price
    group: products-store-project
  name: price-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: price
